### ISSUE TITLE
Documentation - Clarify the IntegerDecoder.int function

### ISSUE THREAD

**Issue by Ololw** [neoxia/apoyo#33]
## 📖 Documentation

It would be nice to add to the "IntegerDecoder.int" function's documentation that there is no autocast from a string.

Maybe it makes sense to reference the "fromString" function in the same documentation, since there is an autocast in others library.

**Comment by sascha245** [comment]
Hello,

Concerning this issue, we have multiple solutions:
- No autocast + add the documentation to avoid such an issue
- Add autocast to the Number / Int Decoder

What would be the best solution here? What would be the inconveniences of each solution?
